name: master

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: garrison-298703
  REGION: us-west2
  GAR_LOCATION: us-west2-docker.pkg.dev/garrison-298703/bolanos-dev-docker

jobs:
  deploy:
    name: build project & upload artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_ACCOUNT_KEY }}'

      - name: 'set up cloud sdk'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: "docker auth"
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: set up jdk
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          overwrite-settings: false
          cache: maven

      - name: maven package
        run: mvn --batch-mode --no-transfer-progress -U clean package

      - name: docker build
        run: docker build . --tag ${{ env.GAR_LOCATION }}/hello-grpc

      - name: docker push
        run: docker push ${{ env.GAR_LOCATION }}/hello-grpc
