name: PR Checks

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          overwrite-settings: false
          cache: maven

      - name: Maven Build & Tests
        run: |
          mvn --batch-mode --no-transfer-progress -U clean verify